### ISSUE TITLE
Tilt Controls

### ISSUE THREAD

**Issue by Adeleine** [libretro/citra#53] opened 2018-11-15 06:41 UTC
Is it currently possible to tilt the screen? I've read that the standalone version of Citra can tilt the screen by clicking on the top screen and dragging the mouse in the direction you want to tilt, but I've tried this using the libretro core and it doesn't work. This is a major issue as it's impossible to complete certain games such as Kirby Triple Deluxe, without being able to tilt the screen.

**Comment by j-selby** [comment] 2018-11-15 13:11
This would depend on whether such functionality is available in the LibRetro API. I haven't looked into this recently, so that would require investigation.

**Comment by j-selby** [comment] 2018-11-15 13:11
Closing as duplicate of #5

**Closed by j-selby** 2018-11-15 13:11 UTC
