### ISSUE TITLE
Partial specialization

### ISSUE THREAD

**Issue by kivutar** [libretro/citra#36] opened 2018-04-22 05:53 UTC
When cross compiling citra on Lakka with gcc7 this time, I'm getting the following errors:

```
[ 40%] Building CXX object src/video_core/CMakeFiles/video_core.dir/renderer_opengl/renderer_opengl.cpp.o
cd /home/kivutar/Lakka-LibreELEC/build.Lakka-Generic.x86_64/citra-db660af/.x86_64-libreelec-linux-gnu/src/video_core && /home/kivutar/Lakka-LibreELEC/build.Lakka-Generic.x86_64/toolchain/bin/x86_64-libreelec-
linux-gnu-g++  -DARCHITECTURE_x86_64=1 -DEMU_ARCH_BITS=64 -DNDEBUG -DSINGLETHREADED -DXBYAK_NO_OP_NAMES -D_FILE_OFFSET_BITS=64 -I/home/kivutar/Lakka-LibreELEC/build.Lakka-Generic.x86_64/citra-db660af/src/. -I
/home/kivutar/Lakka-LibreELEC/build.Lakka-Generic.x86_64/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include -I/home/kivutar/Lakka-LibreELEC/build.Lakka-Generic.x86_64/citra-db660af/externals/fmt/include
 -I/home/kivutar/Lakka-LibreELEC/build.Lakka-Generic.x86_64/citra-db660af/externals/./microprofile -I/home/kivutar/Lakka-LibreELEC/build.Lakka-Generic.x86_64/citra-db660af/externals/glad/include -I/home/kivut
ar/Lakka-LibreELEC/build.Lakka-Generic.x86_64/citra-db660af/externals/./nihstro/include -I/home/kivutar/Lakka-LibreELEC/build.Lakka-Generic.x86_64/citra-db660af/externals/./xbyak/xbyak  -march=x86-64 -m64 -fo
mit-frame-pointer -Wall -pipe -O2 -flto -ffat-lto-objects -mmmx -msse -msse2 -mfpmath=sse -Wno-attributes -fPIC   -std=gnu++1z -o CMakeFiles/video_core.dir/renderer_opengl/renderer_opengl.cpp.o -c /home/kivut
ar/Lakka-LibreELEC/build.Lakka-Generic.x86_64/citra-db660af/src/video_core/renderer_opengl/renderer_opengl.cpp
In file included from /home/kivutar/Lakka-LibreELEC/build.Lakka-Generic.x86_64/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/boost/icl/type_traits/identity_element.hpp:11:0,
                 from /home/kivutar/Lakka-LibreELEC/build.Lakka-Generic.x86_64/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/boost/icl/type_traits/unit_element.hpp:12,
                 from /home/kivutar/Lakka-LibreELEC/build.Lakka-Generic.x86_64/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/boost/icl/concept/interval.hpp:17,
                 from /home/kivutar/Lakka-LibreELEC/build.Lakka-Generic.x86_64/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/boost/icl/concept/joinable.hpp:12,
                 from /home/kivutar/Lakka-LibreELEC/build.Lakka-Generic.x86_64/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/boost/icl/associative_interval_container.hpp:13,
                 from /home/kivutar/Lakka-LibreELEC/build.Lakka-Generic.x86_64/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/boost/icl/interval_base_set.hpp:24,
                 from /home/kivutar/Lakka-LibreELEC/build.Lakka-Generic.x86_64/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/boost/icl/interval_set.hpp:14,
                 from /home/kivutar/Lakka-LibreELEC/build.Lakka-Generic.x86_64/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/boost/icl/interval_map.hpp:13,
                 from /home/kivutar/Lakka-LibreELEC/build.Lakka-Generic.x86_64/citra-db660af/src/./video_core/renderer_opengl/gl_rasterizer_cache.h:15,
                 from /home/kivutar/Lakka-LibreELEC/build.Lakka-Generic.x86_64/citra-db660af/src/./video_core/renderer_opengl/gl_rasterizer.h:26,
                 from /home/kivutar/Lakka-LibreELEC/build.Lakka-Generic.x86_64/citra-db660af/src/video_core/renderer_base.cpp:8:
/home/kivutar/Lakka-LibreELEC/build.Lakka-Generic.x86_64/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/boost/icl/type_traits/type_to_string.hpp:56:12: error: partial specialization of 'struct boost
::icl::type_to_string<Unary<Type> >' after instantiation of 'struct boost::icl::type_to_string<std::basic_string<char> >' [-fpermissive]
     struct type_to_string<Unary<Type> >
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/kivutar/Lakka-LibreELEC/build.Lakka-Generic.x86_64/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/boost/icl/type_traits/type_to_string.hpp:72:12: error: partial specialization of 'struct boost
::icl::type_to_string<Binary<Type1, Type2> >' after instantiation of 'struct boost::icl::type_to_string<std::basic_string<char> >' [-fpermissive]
     struct type_to_string<Binary<Type1, Type2> >
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [src/video_core/CMakeFiles/video_core.dir/build.make:210: src/video_core/CMakeFiles/video_core.dir/renderer_base.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

Any idea how to fix this?

**Comment by j-selby** [comment] 2018-04-22 11:29
Closing. This issue is caused by an outdated version of Boost. Please either use the bundled Boost externals, or update your distro.

**Closed by j-selby** 2018-04-22 11:29 UTC
