### ISSUE TITLE
Build errror: SDL dep

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/citra#33] opened 2018-04-07 00:48 UTC
```
make[4]: Entering directory '/<<PKGBUILDDIR>>/obj-test'
[ 99%] Building CXX object src/dedicated_room/CMakeFiles/citra-room.dir/citra-room.cpp.o
/<<PKGBUILDDIR>>/src/dedicated_room/citra-room.cpp:12:10: fatal error: SDL.h: No such file or directory
 #include <SDL.h>
          ^~~~~~~
compilation terminated.
```

https://launchpadlibrarian.net/360685416/buildlog_ubuntu-artful-amd64.libretro-citra_0.1-r201803141518-7f983fe-10~ubuntu17.10.1_BUILDING.txt.gz

**Comment by j-selby** [comment] 2018-04-07 07:06
Closing as duplicate of #25

**Closed by j-selby** 2018-04-07 07:06 UTC
